/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apartmanotomasyonu;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.UIManager;

/**
 *
 * @author Nurhat
 */
public class girisekranı extends javax.swing.JFrame {

    /**
     * Creates new form girisekranı
     */
    public girisekranı() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yoneticigirisi_btn = new javax.swing.JButton();
        kullanıcıgiris_btn1 = new javax.swing.JButton();
        kullanicimain = new javax.swing.JPanel();
        yöneticipanel = new javax.swing.JPanel();
        yoneticititle = new javax.swing.JLabel();
        yoneticibinano_jbl1 = new javax.swing.JLabel();
        yoneticibinano_jtf1 = new javax.swing.JTextField();
        yoneticisifrelbl = new javax.swing.JLabel();
        yoneticigiris_btn1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        yöneticigirispass = new javax.swing.JPasswordField();
        kullanıcıpanel = new javax.swing.JPanel();
        title_jbl = new javax.swing.JLabel();
        kullanicibinano_jbl = new javax.swing.JLabel();
        kullanicidaireno_jbl = new javax.swing.JLabel();
        daireno_cmb = new javax.swing.JComboBox<>();
        binano_jtf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kullanicigiris_btn = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        yoneticigiris = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        kay_ekr_jlbl = new javax.swing.JLabel();
        yönetici_kaydi_lbl = new javax.swing.JLabel();
        yoneticibinano_jlbl = new javax.swing.JLabel();
        yoneticibinano_jtfk = new javax.swing.JTextField();
        yön_kay_dai_say_jlbl = new javax.swing.JLabel();
        yön_kay_dai_say_jtf = new javax.swing.JTextField();
        yön_kay_şif_jlbl = new javax.swing.JLabel();
        yön_kay_şiftek_jlbl = new javax.swing.JLabel();
        yön_kay_jbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        kay_ekr_kul_jlbl = new javax.swing.JLabel();
        kullanıcı_kaydi_jlbl = new javax.swing.JLabel();
        kull_binano_jlbl = new javax.swing.JLabel();
        kull_kay_daireno_jlbl = new javax.swing.JLabel();
        kull_kay_şif_jlbl = new javax.swing.JLabel();
        kull_kay_şiftek_jlbl = new javax.swing.JLabel();
        kull_kay_jbtn = new javax.swing.JButton();
        kull_binano_jtfk = new javax.swing.JTextField();
        kull_daireno_jtfk = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GİRİŞ YAP");

        yoneticigirisi_btn.setText("Yönetici Girişi");
        yoneticigirisi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticigirisi_btnActionPerformed(evt);
            }
        });

        kullanıcıgiris_btn1.setBackground(new java.awt.Color(51, 255, 255));
        kullanıcıgiris_btn1.setText("Kullanıcı Girişi");
        kullanıcıgiris_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanıcıgiris_btn1ActionPerformed(evt);
            }
        });

        kullanicimain.setLayout(new java.awt.CardLayout());

        yoneticititle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        yoneticititle.setText("Yönetici Girişi");

        yoneticibinano_jbl1.setText("BİNA NO :");

        yoneticisifrelbl.setText("ŞİFRE :");

        yoneticigiris_btn1.setText("GİRİŞ YAP");
        yoneticigiris_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticigiris_btn1ActionPerformed(evt);
            }
        });

        jButton1.setText("göster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yöneticipanelLayout = new javax.swing.GroupLayout(yöneticipanel);
        yöneticipanel.setLayout(yöneticipanelLayout);
        yöneticipanelLayout.setHorizontalGroup(
            yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yöneticipanelLayout.createSequentialGroup()
                .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, yöneticipanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(yoneticititle, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, yöneticipanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yoneticisifrelbl)
                            .addComponent(yoneticibinano_jbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(yöneticipanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(yoneticigiris_btn1))
                            .addComponent(yöneticigirispass, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(yoneticibinano_jtf1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        yöneticipanelLayout.setVerticalGroup(
            yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yöneticipanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(yoneticititle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticibinano_jbl1)
                    .addComponent(yoneticibinano_jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticisifrelbl)
                    .addComponent(yöneticigirispass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(yoneticigiris_btn1)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        kullanicimain.add(yöneticipanel, "card2");

        title_jbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title_jbl.setText("Kullanıcı Girişi");

        kullanicibinano_jbl.setText("BİNA NO :");

        kullanicidaireno_jbl.setText("DAİRE NO :");

        daireno_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("ŞİFRE :");

        kullanicigiris_btn.setText("GİRİŞ YAP");
        kullanicigiris_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanicigiris_btnActionPerformed(evt);
            }
        });

        jButton4.setText("göster");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kullanıcıpanelLayout = new javax.swing.GroupLayout(kullanıcıpanel);
        kullanıcıpanel.setLayout(kullanıcıpanelLayout);
        kullanıcıpanelLayout.setHorizontalGroup(
            kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(kullanicidaireno_jbl)
                            .addComponent(kullanicibinano_jbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kullanicigiris_btn)
                            .addComponent(daireno_cmb, 0, 96, Short.MAX_VALUE)
                            .addComponent(binano_jtf)
                            .addComponent(jPasswordField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(title_jbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        kullanıcıpanelLayout.setVerticalGroup(
            kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(title_jbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanicibinano_jbl)
                    .addComponent(binano_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanicidaireno_jbl)
                    .addComponent(daireno_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(32, 32, 32)
                .addComponent(kullanicigiris_btn)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        kullanicimain.add(kullanıcıpanel, "card3");

        yoneticigiris.setLayout(new java.awt.CardLayout());

        kay_ekr_jlbl.setText("KAYIT OL");

        yönetici_kaydi_lbl.setText("Yönetici Kaydı");

        yoneticibinano_jlbl.setText("BİNA NO :");

        yön_kay_dai_say_jlbl.setText("Daire Sayısı :");

        yön_kay_şif_jlbl.setText("ŞİFRE :");

        yön_kay_şiftek_jlbl.setText("Şifre Tekrarı :");

        yön_kay_jbtn.setText("KAYIT OL");
        yön_kay_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yön_kay_jbtnActionPerformed(evt);
            }
        });

        jButton2.setText("göster");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(kay_ekr_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(yön_kay_şiftek_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(yön_kay_şif_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(yön_kay_dai_say_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(yoneticibinano_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yön_kay_jbtn)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(yön_kay_dai_say_jtf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(yoneticibinano_jtfk, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPasswordField2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(yönetici_kaydi_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(kay_ekr_jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yönetici_kaydi_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticibinano_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yoneticibinano_jtfk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yön_kay_dai_say_jlbl)
                    .addComponent(yön_kay_dai_say_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yön_kay_şif_jlbl)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yön_kay_şiftek_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(yön_kay_jbtn)
                .addContainerGap())
        );

        yoneticigiris.add(jPanel1, "card2");

        kay_ekr_kul_jlbl.setText("KAYIT OL");

        kullanıcı_kaydi_jlbl.setText("Kullanıcı Kaydı");

        kull_binano_jlbl.setText("BİNA NO :");

        kull_kay_daireno_jlbl.setText("Daire NO :");

        kull_kay_şif_jlbl.setText("ŞİFRE :");

        kull_kay_şiftek_jlbl.setText("Şifre Tekrarı :");

        kull_kay_jbtn.setText("KAYIT OL");

        jButton3.setText("göster");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(kull_kay_jbtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kay_ekr_kul_jlbl)
                            .addComponent(kullanıcı_kaydi_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kull_binano_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kull_kay_daireno_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kull_kay_şif_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kull_kay_şiftek_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField5)
                                    .addComponent(kull_binano_jtfk, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(kull_daireno_jtfk)
                                    .addComponent(jPasswordField4, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(kay_ekr_kul_jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kullanıcı_kaydi_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kull_binano_jlbl)
                            .addComponent(kull_binano_jtfk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(kull_kay_daireno_jlbl))
                    .addComponent(kull_daireno_jtfk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kull_kay_şif_jlbl)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kull_kay_şiftek_jlbl)
                    .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(kull_kay_jbtn)
                .addContainerGap())
        );

        yoneticigiris.add(jPanel2, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kullanıcıgiris_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yoneticigirisi_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kullanicimain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(yoneticigiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticigirisi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanıcıgiris_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(kullanicimain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(yoneticigiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yoneticigirisi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticigirisi_btnActionPerformed
        CardLayout card = (CardLayout) kullanicimain.getLayout();
        card.show(kullanicimain, "card2");
        CardLayout card2 = (CardLayout) yoneticigiris.getLayout();
        card2.show(yoneticigiris, "card2");
    }//GEN-LAST:event_yoneticigirisi_btnActionPerformed

    private void kullanıcıgiris_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanıcıgiris_btn1ActionPerformed
        CardLayout card = (CardLayout) kullanicimain.getLayout();
        card.show(kullanicimain, "card3");
        CardLayout card2 = (CardLayout) yoneticigiris.getLayout();
        card2.show(yoneticigiris, "card3");
    }//GEN-LAST:event_kullanıcıgiris_btn1ActionPerformed

    private void yoneticigiris_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticigiris_btn1ActionPerformed
        String url = "jdbc:sqlserver://DESKTOP-T11FMIO;databaseName=APARTMAN;integratedSecurity=True;encrypt=True;trustServerCertificate=True";
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        try {
            // JDBC Sürücüsünü yükle
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // Bağlantıyı başlat
            connection = DriverManager.getConnection(url);
            System.out.println("Bağlantı başarılı!");

            // Kullanıcıdan alınan veriler
            String girilenKullaniciAdi = yoneticibinano_jtf1.getText(); // Kullanıcı adını UI'den çekiyoruz
            String girilenSifre = yöneticigirispass.getText(); // Şifreyi UI'den çekiyoruz

            // SQL'den kullanıcı adı ve şifreyi seçiyoruz
            String selectSQL = "SELECT Bina_No, şifre FROM yötici_kayitlari_table WHERE Bina_No = ?";

            preparedStatement = connection.prepareStatement(selectSQL);
            preparedStatement.setString(1, girilenKullaniciAdi); // SQL'deki '?' yerine girilen kullanıcı adını koyuyoruz
            resultSet = preparedStatement.executeQuery();

            // Eğer sonuç varsa
            if (resultSet.next()) {
                String veritabanindakiSifre = resultSet.getString("şifre");

                // Girilen şifreyle veritabanındaki şifreyi karşılaştırıyoruz
                if (veritabanindakiSifre.equals(girilenSifre)) {
                    System.out.println("Bina_No adı ve şifre doğru, işlem başarılı!");
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new yöneticiekrani().setVisible(true);
                        }
                    });
                    // Burada gerekli işlemleri yapabilirsiniz
                } else {
                    System.out.println("Şifre yanlış.");
                }
            } else {
                System.out.println("Kullanıcı adı bulunamadı.");
            }

        } catch (ClassNotFoundException e) {
            System.err.println("SQL Server JDBC sürücüsü bulunamadı.");
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (resultSet != null) {
                    resultSet.close();
                }
                if (preparedStatement != null) {
                    preparedStatement.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_yoneticigiris_btn1ActionPerformed

    private void kullanicigiris_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanicigiris_btnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullaniciekrani().setVisible(true);
            }
        });
    }//GEN-LAST:event_kullanicigiris_btnActionPerformed

    private void yön_kay_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yön_kay_jbtnActionPerformed
        String url = "jdbc:sqlserver://DESKTOP-T11FMIO;databaseName=APARTMAN;integratedSecurity=True;encrypt=True;trustServerCertificate=True";
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        try {
            // JDBC Sürücüsünü yükle
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // Bağlantıyı başlat
            connection = DriverManager.getConnection(url);
            System.out.println("Bağlantı başarılı!");

            // Parametreli sorgu
            String insertSQL = "INSERT INTO yötici_kayitlari_table (Bina_No, Daire_Sayısı,şifre) VALUES (?, ?, ?)";

            // PreparedStatement oluştur
            preparedStatement = connection.prepareStatement(insertSQL);

            // Parametreleri ayarla (Örnek veriler: "değer1", 123)
            preparedStatement.setString(1, yoneticibinano_jtfk.getText());
            preparedStatement.setInt(2, Integer.parseInt(yön_kay_dai_say_jtf.getText()));
            if (jPasswordField1.getText().equals(jPasswordField2.getText())) {
                preparedStatement.setString(3, jPasswordField2.getText());
            }

            // Sorguyu çalıştır
            int rowsInserted = preparedStatement.executeUpdate();
            if (rowsInserted > 0) {
                System.out.println("Kayıt başarıyla eklendi!");
            }

        } catch (ClassNotFoundException e) {
            // Sürücü yükleme hatası
            System.err.println("SQL Server JDBC sürücüsü bulunamadı.");
            e.printStackTrace();
        } catch (SQLException e) {
            // Bağlantı veya sorgu hatası
            e.printStackTrace();
        } finally {
            // Kaynakları kapat
            try {
                if (resultSet != null) {
                    resultSet.close();
                }
                if (preparedStatement != null) {
                    preparedStatement.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_yön_kay_jbtnActionPerformed
    private boolean isVisible = false;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (isVisible) {
            yöneticigirispass.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jButton1.setText("Göster");
        } else {
            yöneticigirispass.setEchoChar((char) 0); // Şifreyi göster
            jButton1.setText("Gizle");
        }
        isVisible = !isVisible;


    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean isVisible2 = false;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (isVisible2) {
            jPasswordField1.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jPasswordField2.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jButton2.setText("Göster");
        } else {
            jPasswordField1.setEchoChar((char) 0); // Şifreyi göster
            jPasswordField2.setEchoChar((char) 0); // Şifreyi göster
            jButton2.setText("Gizle");
        }
        isVisible2 = !isVisible2;

    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean isVisible3 = false;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (isVisible3) {
            jPasswordField3.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jButton4.setText("Göster");
        } else {
            jPasswordField3.setEchoChar((char) 0); // Şifreyi göster
            jButton4.setText("Gizle");
        }
        isVisible3 = !isVisible3;
    }//GEN-LAST:event_jButton4ActionPerformed
    private boolean isVisible4 = false;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (isVisible4) {
            jPasswordField4.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jPasswordField5.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jButton3.setText("Göster");
        } else {
            jPasswordField4.setEchoChar((char) 0); // Şifreyi göster
            jPasswordField5.setEchoChar((char) 0); // Şifreyi göster
            jButton3.setText("Gizle");
        }
        isVisible4 = !isVisible4;
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girisekranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField binano_jtf;
    private javax.swing.JComboBox<String> daireno_cmb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JLabel kay_ekr_jlbl;
    private javax.swing.JLabel kay_ekr_kul_jlbl;
    private javax.swing.JLabel kull_binano_jlbl;
    private javax.swing.JTextField kull_binano_jtfk;
    private javax.swing.JTextField kull_daireno_jtfk;
    private javax.swing.JLabel kull_kay_daireno_jlbl;
    private javax.swing.JButton kull_kay_jbtn;
    private javax.swing.JLabel kull_kay_şif_jlbl;
    private javax.swing.JLabel kull_kay_şiftek_jlbl;
    private javax.swing.JLabel kullanicibinano_jbl;
    private javax.swing.JLabel kullanicidaireno_jbl;
    private javax.swing.JButton kullanicigiris_btn;
    private javax.swing.JPanel kullanicimain;
    private javax.swing.JLabel kullanıcı_kaydi_jlbl;
    private javax.swing.JButton kullanıcıgiris_btn1;
    private javax.swing.JPanel kullanıcıpanel;
    private javax.swing.JLabel title_jbl;
    private javax.swing.JLabel yoneticibinano_jbl1;
    private javax.swing.JLabel yoneticibinano_jlbl;
    private javax.swing.JTextField yoneticibinano_jtf1;
    private javax.swing.JTextField yoneticibinano_jtfk;
    private javax.swing.JPanel yoneticigiris;
    private javax.swing.JButton yoneticigiris_btn1;
    private javax.swing.JButton yoneticigirisi_btn;
    private javax.swing.JLabel yoneticisifrelbl;
    private javax.swing.JLabel yoneticititle;
    private javax.swing.JLabel yön_kay_dai_say_jlbl;
    private javax.swing.JTextField yön_kay_dai_say_jtf;
    private javax.swing.JButton yön_kay_jbtn;
    private javax.swing.JLabel yön_kay_şif_jlbl;
    private javax.swing.JLabel yön_kay_şiftek_jlbl;
    private javax.swing.JLabel yönetici_kaydi_lbl;
    private javax.swing.JPasswordField yöneticigirispass;
    private javax.swing.JPanel yöneticipanel;
    // End of variables declaration//GEN-END:variables
}
