/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apartmanotomasyonu;

import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Nurhat
 */
public class girisekranı extends javax.swing.JFrame {

    /**
     * Creates new form girisekranı
     */
    public girisekranı() {
        initComponents();
        setLocationRelativeTo(null);
        binano_jtf.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cmbdolur();

            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                cmbdolur();

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                cmbdolur();

            }
        });
        kull_binano_jtfk.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {

                cmbdolurkayıt();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {

                cmbdolurkayıt();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

                cmbdolurkayıt();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yoneticigirisi_btn = new javax.swing.JButton();
        kullanıcıgiris_btn1 = new javax.swing.JButton();
        kullanicimain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        yöneticipanel = new javax.swing.JPanel();
        yoneticititle = new javax.swing.JLabel();
        yoneticibinano_jbl1 = new javax.swing.JLabel();
        yoneticibinano_jtf1 = new javax.swing.JTextField();
        yoneticisifrelbl = new javax.swing.JLabel();
        yoneticigiris_btn1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        yöneticigirispass = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        yön_gr_hata_lbli = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        kay_ekr_jlbl = new javax.swing.JLabel();
        yönetici_kaydi_lbl = new javax.swing.JLabel();
        yoneticibinano_jlbl = new javax.swing.JLabel();
        yoneticibinano_jtfk = new javax.swing.JTextField();
        yön_kay_dai_say_jlbl = new javax.swing.JLabel();
        yön_kay_dai_say_jtf = new javax.swing.JTextField();
        yön_kay_şif_jlbl = new javax.swing.JLabel();
        yön_kay_şiftek_jlbl = new javax.swing.JLabel();
        yön_kay_jbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        kullanıcıpanel = new javax.swing.JPanel();
        title_jbl = new javax.swing.JLabel();
        kullanicibinano_jbl = new javax.swing.JLabel();
        kullanicidaireno_jbl = new javax.swing.JLabel();
        daireno_cmb = new javax.swing.JComboBox<>();
        binano_jtf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kullanicigiris_btn = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        kul_gir_hata_lbli = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        kay_ekr_kul_jlbl = new javax.swing.JLabel();
        kullanıcı_kaydi_jlbl = new javax.swing.JLabel();
        kull_binano_jlbl = new javax.swing.JLabel();
        kull_kay_daireno_jlbl = new javax.swing.JLabel();
        kull_kay_şif_jlbl = new javax.swing.JLabel();
        kull_kay_şiftek_jlbl = new javax.swing.JLabel();
        kull_kay_jbtn = new javax.swing.JButton();
        kull_binano_jtfk = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GİRİŞ YAP");
        setBackground(new java.awt.Color(25, 183, 244));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        yoneticigirisi_btn.setBackground(new java.awt.Color(255, 0, 204));
        yoneticigirisi_btn.setText("Yönetici Girişi");
        yoneticigirisi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticigirisi_btnActionPerformed(evt);
            }
        });

        kullanıcıgiris_btn1.setBackground(new java.awt.Color(51, 255, 255));
        kullanıcıgiris_btn1.setText("Kullanıcı Girişi");
        kullanıcıgiris_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanıcıgiris_btn1ActionPerformed(evt);
            }
        });

        kullanicimain.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new java.awt.CardLayout());

        yöneticipanel.setBackground(new java.awt.Color(255, 0, 204));

        yoneticititle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        yoneticititle.setText("Yönetici Girişi");

        yoneticibinano_jbl1.setText("BİNA NO :");

        yoneticisifrelbl.setText("ŞİFRE :");

        yoneticigiris_btn1.setText("GİRİŞ YAP");
        yoneticigiris_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticigiris_btn1ActionPerformed(evt);
            }
        });

        jButton1.setText("göster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Kayıt Ol");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        yön_gr_hata_lbli.setBackground(new java.awt.Color(255, 0, 0));
        yön_gr_hata_lbli.setForeground(new java.awt.Color(255, 0, 0));
        yön_gr_hata_lbli.setText(" ");

        javax.swing.GroupLayout yöneticipanelLayout = new javax.swing.GroupLayout(yöneticipanel);
        yöneticipanel.setLayout(yöneticipanelLayout);
        yöneticipanelLayout.setHorizontalGroup(
            yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yöneticipanelLayout.createSequentialGroup()
                .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yöneticipanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(yoneticititle, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(yöneticipanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yoneticisifrelbl)
                            .addComponent(yoneticibinano_jbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(yöneticipanelLayout.createSequentialGroup()
                                .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yöneticigirispass, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(yoneticibinano_jtf1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(yöneticipanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(yoneticigiris_btn1))))
                    .addGroup(yöneticipanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(yön_gr_hata_lbli, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        yöneticipanelLayout.setVerticalGroup(
            yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yöneticipanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticititle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(37, 37, 37)
                .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticibinano_jbl1)
                    .addComponent(yoneticibinano_jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(yöneticipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticisifrelbl)
                    .addComponent(yöneticigirispass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yön_gr_hata_lbli)
                .addGap(18, 18, 18)
                .addComponent(yoneticigiris_btn1)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jPanel3.add(yöneticipanel, "card2");

        jPanel1.setBackground(new java.awt.Color(255, 0, 204));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));

        kay_ekr_jlbl.setText("KAYIT OL");

        yönetici_kaydi_lbl.setText("Yönetici Kaydı");

        yoneticibinano_jlbl.setText("BİNA NO :");

        yön_kay_dai_say_jlbl.setText("Daire Sayısı :");

        yön_kay_şif_jlbl.setText("ŞİFRE :");

        yön_kay_şiftek_jlbl.setText("Şifre Tekrarı :");

        yön_kay_jbtn.setText("KAYIT OL");
        yön_kay_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yön_kay_jbtnActionPerformed(evt);
            }
        });

        jButton2.setText("göster");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setText("Giriş Yap");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(kay_ekr_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(yön_kay_şiftek_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(yön_kay_şif_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(yön_kay_dai_say_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(yoneticibinano_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yön_kay_jbtn)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(yön_kay_dai_say_jtf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(yoneticibinano_jtfk, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPasswordField2))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(yönetici_kaydi_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(kay_ekr_jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yönetici_kaydi_lbl)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticibinano_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yoneticibinano_jtfk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yön_kay_dai_say_jlbl)
                    .addComponent(yön_kay_dai_say_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yön_kay_şif_jlbl)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yön_kay_şiftek_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(yön_kay_jbtn)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, "card3");

        kullanicimain.add(jPanel3, "card2");

        jPanel4.setLayout(new java.awt.CardLayout());

        kullanıcıpanel.setBackground(new java.awt.Color(0, 255, 255));

        title_jbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title_jbl.setText("Kullanıcı Girişi");

        kullanicibinano_jbl.setText("BİNA NO :");

        kullanicidaireno_jbl.setText("DAİRE NO :");

        daireno_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        daireno_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daireno_cmbActionPerformed(evt);
            }
        });

        jLabel1.setText("ŞİFRE :");

        kullanicigiris_btn.setText("GİRİŞ YAP");
        kullanicigiris_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanicigiris_btnActionPerformed(evt);
            }
        });

        jButton4.setText("göster");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Kayıt Ol");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        kul_gir_hata_lbli.setText(" ");

        javax.swing.GroupLayout kullanıcıpanelLayout = new javax.swing.GroupLayout(kullanıcıpanel);
        kullanıcıpanel.setLayout(kullanıcıpanelLayout);
        kullanıcıpanelLayout.setHorizontalGroup(
            kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(title_jbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(kullanicidaireno_jbl)
                            .addComponent(kullanicibinano_jbl)))
                    .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kul_gir_hata_lbli, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kullanicigiris_btn)
                                    .addComponent(daireno_cmb, 0, 96, Short.MAX_VALUE)
                                    .addComponent(binano_jtf)
                                    .addComponent(jPasswordField3))
                                .addGap(16, 16, 16)
                                .addComponent(jButton4)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        kullanıcıpanelLayout.setVerticalGroup(
            kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanıcıpanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_jbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(34, 34, 34)
                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanicibinano_jbl)
                    .addComponent(binano_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanicidaireno_jbl)
                    .addComponent(daireno_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kullanıcıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(46, 46, 46)
                .addComponent(kul_gir_hata_lbli)
                .addGap(12, 12, 12)
                .addComponent(kullanicigiris_btn)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jPanel4.add(kullanıcıpanel, "card2");

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        kay_ekr_kul_jlbl.setText("KAYIT OL");

        kullanıcı_kaydi_jlbl.setText("Kullanıcı Kaydı");

        kull_binano_jlbl.setText("BİNA NO :");

        kull_kay_daireno_jlbl.setText("Daire NO :");

        kull_kay_şif_jlbl.setText("ŞİFRE :");

        kull_kay_şiftek_jlbl.setText("Şifre Tekrarı :");

        kull_kay_jbtn.setText("KAYIT OL");
        kull_kay_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kull_kay_jbtnActionPerformed(evt);
            }
        });

        kull_binano_jtfk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kull_binano_jtfkActionPerformed(evt);
            }
        });

        jPasswordField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField4ActionPerformed(evt);
            }
        });

        jPasswordField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField5ActionPerformed(evt);
            }
        });

        jButton3.setText("göster");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Giriş yap");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kay_ekr_kul_jlbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kullanıcı_kaydi_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(23, 23, 23))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kull_binano_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kull_kay_daireno_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kull_kay_şif_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kull_kay_şiftek_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField5)
                                    .addComponent(kull_binano_jtfk, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jPasswordField4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(kull_kay_jbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(kay_ekr_kul_jlbl)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kullanıcı_kaydi_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kull_binano_jlbl)
                    .addComponent(kull_binano_jtfk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kull_kay_daireno_jlbl)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kull_kay_şif_jlbl)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kull_kay_şiftek_jlbl)
                    .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(kull_kay_jbtn)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, "card3");

        kullanicimain.add(jPanel4, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kullanıcıgiris_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yoneticigirisi_btn))
                    .addComponent(kullanicimain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticigirisi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanıcıgiris_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(kullanicimain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yoneticigirisi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticigirisi_btnActionPerformed
        CardLayout card = (CardLayout) kullanicimain.getLayout();
        card.show(kullanicimain, "card2");

    }//GEN-LAST:event_yoneticigirisi_btnActionPerformed

    private void kullanıcıgiris_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanıcıgiris_btn1ActionPerformed
        CardLayout card = (CardLayout) kullanicimain.getLayout();
        card.show(kullanicimain, "card3");

    }//GEN-LAST:event_kullanıcıgiris_btn1ActionPerformed
    public static String bina_no;
    private void yoneticigiris_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticigiris_btn1ActionPerformed
        SQLHelper dbhelper = new SQLHelper();

        String sql = "SELECT Bina_No, şifre FROM yötici_kayitlari_table WHERE Bina_No = ?";

        String girilenKullaniciAdi = yoneticibinano_jtf1.getText(); // Kullanıcı adını UI'den çekiyoruz
        String girilenSifre = yöneticigirispass.getText(); // Şifreyi UI'den çekiyoruz

        try (ResultSet rs = dbhelper.executeQuery(sql, girilenKullaniciAdi)) {

            if (rs.next()) {
                String veritabanindakiSifre = rs.getString("şifre");
                // Girilen şifreyle veritabanındaki şifreyi karşılaştırıyoruz
                if (veritabanindakiSifre.equals(girilenSifre)) {
                    bina_no=yoneticibinano_jtf1.getText();
                    System.out.println("Bina_No adı ve şifre doğru, işlem başarılı!");
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new yöneticiekrani().setVisible(true);
                            
                        }
                    });
                    // Burada gerekli işlemleri yapabilirsiniz
                } else {
                    yön_gr_hata_lbli.setText("Bina no ve/veya şifre yanlış");
                }
            } else {
                yön_gr_hata_lbli.setText("Bina no ve/veya şifre yanlış");
            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }


    }//GEN-LAST:event_yoneticigiris_btn1ActionPerformed

    private void kullanicigiris_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanicigiris_btnActionPerformed

        SQLHelper dbhelper = new SQLHelper();

        String sql = "SELECT Bina_No, şifre FROM kullaniciler_table WHERE Bina_No = ? and daire_no = ?";
        String girilenKullaniciAdi = binano_jtf.getText(); // Kullanıcı adını UI'den çekiyoruz
        String secilenVeri = (String) daireno_cmb.getSelectedItem();
        int index = secilenVeri.indexOf(": ");
        String daireNoStr = secilenVeri.substring(index + 2);
        String girilenSifre = jPasswordField3.getText();

        try (ResultSet rs = dbhelper.executeQuery(sql, girilenKullaniciAdi, daireNoStr)) {

            if (rs.next()) {
                String veritabanindakiSifre = rs.getString("şifre");

                // Girilen şifreyle veritabanındaki şifreyi karşılaştırıyoruz
                if (veritabanindakiSifre.equals(girilenSifre)) {
                    System.out.println("Bina_No adı ve şifre doğru, işlem başarılı!");
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new kullaniciekrani().setVisible(true);
                        }
                    });
                    // Burada gerekli işlemleri yapabilirsiniz
                } else {
                    kul_gir_hata_lbli.setText("Bina no ve/veya şifre yanlış");
                }
            } else {
                kul_gir_hata_lbli.setText("Bina no ve/veya şifre yanlış");
            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }


    }//GEN-LAST:event_kullanicigiris_btnActionPerformed

    private void yön_kay_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yön_kay_jbtnActionPerformed
        SQLHelper dbhelper = new SQLHelper();

        // Parametreli sorgu (önce kayıt var mı kontrol et)
        String checkSQL = "SELECT COUNT(*) FROM yötici_kayitlari_table WHERE Bina_No = ? and Daire_Sayısı = ?";

        try (ResultSet rs = dbhelper.executeQuery(checkSQL, yoneticibinano_jtfk.getText(), yön_kay_dai_say_jtf.getText())) {
            while (rs != null && rs.next()) {
                int count = rs.getInt(1);
                if (count > 0) {
                    // Eğer kayıt varsa, hata mesajı
                    jLabel3.setText("Bu bina no ve daire no için zaten kayıt bulunuyor!");
                    return;  // İşlem sonlandırılır
                }
            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }

        // Kayıt var mı kontrol et
        // Eğer kayıt yoksa, yeni veriyi ekle
        String insertSQL = "INSERT INTO yötici_kayitlari_table (Bina_No, Daire_Sayısı,şifre) VALUES (?, ?, ?)";
        if (jPasswordField1.getText().equals(jPasswordField2.getText())) {

            // Veritabanına ekleme işlemi
            int result = dbhelper.executeUpdate(insertSQL, yoneticibinano_jtfk.getText(), yön_kay_dai_say_jtf.getText(), jPasswordField2.getText());
            if (result > 0) {
                System.out.println("Veri başarıyla eklendi.");
            } else {
                jLabel3.setText("Veri ekleme başarısız.");
                System.err.println("Veri ekleme başarısız.");
            }
            dbhelper.close();

            if (result > 0) {
                System.out.println("Kayıt başarıyla eklendi!");
                jLabel3.setText("Kayıt başarıyla eklendi!");
            }
        } else {
            jLabel3.setText("Şifre ve şifre tekrarı aynı değil.");
        }


    }//GEN-LAST:event_yön_kay_jbtnActionPerformed
    private boolean isVisible = false;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (isVisible) {
            yöneticigirispass.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jButton1.setText("Göster");
        } else {
            yöneticigirispass.setEchoChar((char) 0); // Şifreyi göster
            jButton1.setText("Gizle");
        }
        isVisible = !isVisible;


    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean isVisible2 = false;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (isVisible2) {
            jPasswordField1.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jPasswordField2.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jButton2.setText("Göster");
        } else {
            jPasswordField1.setEchoChar((char) 0); // Şifreyi göster
            jPasswordField2.setEchoChar((char) 0); // Şifreyi göster
            jButton2.setText("Gizle");
        }
        isVisible2 = !isVisible2;

    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean isVisible3 = false;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (isVisible3) {
            jPasswordField3.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jButton4.setText("Göster");
        } else {
            jPasswordField3.setEchoChar((char) 0); // Şifreyi göster
            jButton4.setText("Gizle");
        }
        isVisible3 = !isVisible3;
    }//GEN-LAST:event_jButton4ActionPerformed
    private boolean isVisible4 = false;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (isVisible4) {
            jPasswordField4.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jPasswordField5.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // Varsayılan gizleme karakterini geri yükle
            jButton3.setText("Göster");
        } else {
            jPasswordField4.setEchoChar((char) 0); // Şifreyi göster
            jPasswordField5.setEchoChar((char) 0); // Şifreyi göster
            jButton3.setText("Gizle");
        }
        isVisible4 = !isVisible4;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout card = (CardLayout) jPanel4.getLayout();
        card.show(jPanel4, "card2");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CardLayout card = (CardLayout) jPanel4.getLayout();
        card.show(jPanel4, "card3");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        CardLayout card = (CardLayout) jPanel3.getLayout();
        card.show(jPanel3, "card2");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout card = (CardLayout) jPanel3.getLayout();
        card.show(jPanel3, "card3");
    }//GEN-LAST:event_jButton6ActionPerformed
    private void cmbdolur() {

        // SQL bağlantı bilgileri
        SQLHelper dbhelper = new SQLHelper();

        String sql = "SELECT Daire_Sayısı FROM yötici_kayitlari_table WHERE Bina_No = ?";
        daireno_cmb.removeAllItems();
        try (ResultSet rs = dbhelper.executeQuery(sql, binano_jtf.getText())) {

            if (rs.next()) {
                int daireSayisi = rs.getInt("Daire_Sayısı");

                // Şimdi daire numaralarını ComboBox'a ekleyelim
                for (int i = 1; i <= daireSayisi; i++) {
                    daireno_cmb.addItem("Daire No: " + i);
                }
            } else {
                daireno_cmb.removeAllItems(); // Kayıt bulunmazsa ComboBox'u temizleyin
            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }

    }

    private void cmbdolurkayıt() {

        // SQL bağlantı bilgileri
        SQLHelper dbhelper = new SQLHelper();

        String sql = "SELECT Daire_Sayısı FROM yötici_kayitlari_table WHERE Bina_No = ?";
        jComboBox1.removeAllItems();
        try (ResultSet rs = dbhelper.executeQuery(sql, kull_binano_jtfk.getText())) {

            if (rs.next()) {
                int daireSayisi = rs.getInt("Daire_Sayısı");

                // Şimdi daire numaralarını ComboBox'a ekleyelim
                for (int i = 1; i <= daireSayisi; i++) {
                    jComboBox1.addItem("Daire No: " + i);
                }
            } else {
                jComboBox1.removeAllItems(); // Kayıt bulunmazsa ComboBox'u temizleyin
            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }

    }
    private void daireno_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daireno_cmbActionPerformed


    }//GEN-LAST:event_daireno_cmbActionPerformed

    private void kull_kay_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kull_kay_jbtnActionPerformed
        SQLHelper sql = new SQLHelper();

        // Parametreli sorgu (önce kayıt var mı kontrol et)
        String checkSQL = "SELECT COUNT(*) FROM kullaniciler_table WHERE bina_no = ? AND daire_no = ?";
        String secilenVeri = (String) jComboBox1.getSelectedItem();
        int index = secilenVeri.indexOf(": ");
        String daireNoStr = secilenVeri.substring(index + 2); // ": " karakterinden sonrası
        try (ResultSet rs = sql.executeQuery(checkSQL, kull_binano_jtfk.getText(), daireNoStr)) {
            while (rs != null && rs.next()) {
                int count = rs.getInt(1);
                if (count > 0) {
                    // Eğer kayıt varsa, hata mesajı
                    jLabel2.setText("Bu bina no ve daire no için zaten kayıt bulunuyor!");
                    return;  // İşlem sonlandırılır
                }
            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }

        // Kayıt var mı kontrol et
        // Eğer kayıt yoksa, yeni veriyi ekle
        String insertSQL = "INSERT INTO kullaniciler_table (bina_no, daire_no, şifre) VALUES (?, ?, ?)";
        if (jPasswordField4.getText().equals(jPasswordField5.getText())) {

            // Veritabanına ekleme işlemi
            int result = sql.executeUpdate(insertSQL, kull_binano_jtfk.getText(), daireNoStr, jPasswordField5.getText());
            if (result > 0) {
                System.out.println("Veri başarıyla eklendi.");
            } else {
                System.err.println("Veri ekleme başarısız.");
            }
            sql.close();

            if (result > 0) {
                System.out.println("Kayıt başarıyla eklendi!");
                jLabel2.setText("Kayıt başarıyla eklendi!");
            }
        } else {
            jLabel2.setText("Şifre ve şifre tekrarı aynı değil.");
        }


    }//GEN-LAST:event_kull_kay_jbtnActionPerformed

    private void kull_binano_jtfkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kull_binano_jtfkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kull_binano_jtfkActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jPasswordField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField4ActionPerformed

    private void jPasswordField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisekranı.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisekranı.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisekranı.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisekranı.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girisekranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField binano_jtf;
    private javax.swing.JComboBox<String> daireno_cmb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JLabel kay_ekr_jlbl;
    private javax.swing.JLabel kay_ekr_kul_jlbl;
    private javax.swing.JLabel kul_gir_hata_lbli;
    private javax.swing.JLabel kull_binano_jlbl;
    private javax.swing.JTextField kull_binano_jtfk;
    private javax.swing.JLabel kull_kay_daireno_jlbl;
    private javax.swing.JButton kull_kay_jbtn;
    private javax.swing.JLabel kull_kay_şif_jlbl;
    private javax.swing.JLabel kull_kay_şiftek_jlbl;
    private javax.swing.JLabel kullanicibinano_jbl;
    private javax.swing.JLabel kullanicidaireno_jbl;
    private javax.swing.JButton kullanicigiris_btn;
    private javax.swing.JPanel kullanicimain;
    private javax.swing.JLabel kullanıcı_kaydi_jlbl;
    private javax.swing.JButton kullanıcıgiris_btn1;
    private javax.swing.JPanel kullanıcıpanel;
    private javax.swing.JLabel title_jbl;
    private javax.swing.JLabel yoneticibinano_jbl1;
    private javax.swing.JLabel yoneticibinano_jlbl;
    private javax.swing.JTextField yoneticibinano_jtf1;
    private javax.swing.JTextField yoneticibinano_jtfk;
    private javax.swing.JButton yoneticigiris_btn1;
    private javax.swing.JButton yoneticigirisi_btn;
    private javax.swing.JLabel yoneticisifrelbl;
    private javax.swing.JLabel yoneticititle;
    private javax.swing.JLabel yön_gr_hata_lbli;
    private javax.swing.JLabel yön_kay_dai_say_jlbl;
    private javax.swing.JTextField yön_kay_dai_say_jtf;
    private javax.swing.JButton yön_kay_jbtn;
    private javax.swing.JLabel yön_kay_şif_jlbl;
    private javax.swing.JLabel yön_kay_şiftek_jlbl;
    private javax.swing.JLabel yönetici_kaydi_lbl;
    private javax.swing.JPasswordField yöneticigirispass;
    private javax.swing.JPanel yöneticipanel;
    // End of variables declaration//GEN-END:variables
}
