/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apartmanotomasyonu;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nurhat
 */
public class kullaniciekrani extends javax.swing.JFrame {

    /**
     * Creates new form kullaniciekrani
     */
    public kullaniciekrani() {
        initComponents();
        setLocationRelativeTo(null);
        gelirlerdoldur();
        gelirlerdoldur2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        kull_ekr_aidat_jbtn = new javax.swing.JButton();
        kull_ekr_bin_gideri_jbtn = new javax.swing.JButton();
        kull_ekr_ust_lbl1 = new javax.swing.JLabel();
        kullanicitablomain_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kull_ekr_tbl1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        kull_ekr_tbl2 = new javax.swing.JTable();
        kull_ekr_ustlbl2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kull_ekr_aidat_jbtn.setBackground(new java.awt.Color(0, 0, 255));
        kull_ekr_aidat_jbtn.setText("Aidatlarınız");
        kull_ekr_aidat_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kull_ekr_aidat_jbtnActionPerformed(evt);
            }
        });

        kull_ekr_bin_gideri_jbtn.setBackground(new java.awt.Color(255, 0, 0));
        kull_ekr_bin_gideri_jbtn.setText("Bina giderleri");
        kull_ekr_bin_gideri_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kull_ekr_bin_gideri_jbtnActionPerformed(evt);
            }
        });

        kull_ekr_ust_lbl1.setBackground(new java.awt.Color(51, 255, 0));
        kull_ekr_ust_lbl1.setText("Bu ayki aidatı ödediniz.");
        kull_ekr_ust_lbl1.setOpaque(true);

        kullanicitablomain_panel.setLayout(new java.awt.CardLayout());

        kull_ekr_tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(kull_ekr_tbl1);

        kullanicitablomain_panel.add(jScrollPane1, "card2");

        kull_ekr_tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(kull_ekr_tbl2);

        kullanicitablomain_panel.add(jScrollPane2, "card3");

        kull_ekr_ustlbl2.setBackground(new java.awt.Color(51, 255, 0));
        kull_ekr_ustlbl2.setText("Ekstra bina masrafını ödediniz.");
        kull_ekr_ustlbl2.setOpaque(true);

        jLabel1.setText("Bina giderinin dekontunu görüntüle ");

        jLabel2.setText("Dekont ID:");

        jButton1.setText("Dekontu Görüntüle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kullanicitablomain_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(kull_ekr_bin_gideri_jbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kull_ekr_aidat_jbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kull_ekr_ust_lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kull_ekr_ustlbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner1)))
                    .addComponent(jButton1))
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kull_ekr_ust_lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kull_ekr_ustlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kull_ekr_bin_gideri_jbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kull_ekr_aidat_jbtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kullanicitablomain_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void gelirlerdoldur() {
        SQLHelper dphelper = new SQLHelper();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Bina No");
        model.addColumn("Tarih");
        model.addColumn("Gider Türü");
        model.addColumn("Miktar");
        model.addColumn("Dekont Resmi");

        String selectSQL = "SELECT id,Bina_no, tarih, Gidar_Türü, miktar, dekont FROM Bina_Giderleri_table where Bina_no=?";
        try (ResultSet rs = dphelper.executeQuery(selectSQL, girisekranı.bina_no)) {

            while (rs.next()) {

                Vector<Object> row = new Vector<>();
                row.add(rs.getInt("id"));
                row.add(rs.getInt("Bina_no"));
                row.add(rs.getString("tarih"));
                row.add(rs.getString("Gidar_Türü"));
                row.add(rs.getObject("miktar"));
                row.add(rs.getObject("dekont"));

                // Her satır için bir buton yerleştirme
                model.addRow(row);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        kull_ekr_tbl1.setModel(model);
        kull_ekr_tbl1.setRowHeight(40); // Satır yüksekliği butonlar için ayarlanır
    }
public void gelirlerdoldur2() {
        SQLHelper dphelper = new SQLHelper();
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Bina No");
        model.addColumn("Daire No");
        model.addColumn("Tarih");
        
        model.addColumn("Miktar");
       

        String selectSQL = "SELECT bina_no, Daire_no, Tarih, miktar FROM aidat_gelirleri_table where Bina_no=? and Daire_no=?";
        try (ResultSet rs = dphelper.executeQuery(selectSQL, girisekranı.bina_no,girisekranı.daire_no)) {

            while (rs.next()) {

                Vector<Object> row = new Vector<>();
                
                row.add(rs.getInt("bina_no"));
                row.add(rs.getString("Daire_no"));
                row.add(rs.getString("Tarih"));
                row.add(rs.getObject("miktar"));
                

                // Her satır için bir buton yerleştirme
                model.addRow(row);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        kull_ekr_tbl2.setModel(model);
        kull_ekr_tbl2.setRowHeight(40); // Satır yüksekliği butonlar için ayarlanır
    }
    private void kull_ekr_aidat_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kull_ekr_aidat_jbtnActionPerformed
        CardLayout card = (CardLayout) kullanicitablomain_panel.getLayout();
        card.show(kullanicitablomain_panel, "card3");
    }//GEN-LAST:event_kull_ekr_aidat_jbtnActionPerformed

    private void kull_ekr_bin_gideri_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kull_ekr_bin_gideri_jbtnActionPerformed
        CardLayout card = (CardLayout) kullanicitablomain_panel.getLayout();
        card.show(kullanicitablomain_panel, "card2");
    }//GEN-LAST:event_kull_ekr_bin_gideri_jbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SQLHelper dphelper = new SQLHelper();

        String selectSQL = "SELECT dekont FROM Bina_Giderleri_table where id=? and Bina_no=?";
        try (ResultSet rs = dphelper.executeQuery(selectSQL, jSpinner1.getValue(),girisekranı.bina_no)) {
            if (rs.next()) {
                // Veriyi alıyoruz
                byte[] imageBytes = rs.getBytes("dekont");

                if (imageBytes != null) {
                    // Byte dizisini BufferedImage'ye çeviriyoruz
                    InputStream in = new ByteArrayInputStream(imageBytes);
                    BufferedImage img = ImageIO.read(in);

                    // Ekran boyutlarını alıyoruz
                    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                    int screenWidth = (int) screenSize.getWidth();
                    int screenHeight = (int) screenSize.getHeight();

                    // Resmin boyutlarını ekran boyutuna göre ayarlıyoruz
                    int imgWidth = img.getWidth();
                    int imgHeight = img.getHeight();

                    // Resmin boyutunu ekran boyutlarına sığacak şekilde yeniden boyutlandırıyoruz
                    int newWidth = Math.min(imgWidth, screenWidth - 100); // Ekranın biraz daha küçük olması için 100 piksel boşluk bırakıyoruz
                    int newHeight = Math.min(imgHeight, screenHeight - 100); // Aynı şekilde yükseklik için de

                    // Resmi yeniden boyutlandırıyoruz
                    Image scaledImage = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
                    ImageIcon scaledIcon = new ImageIcon(scaledImage);

                    // Yeni bir frame açıyoruz
                    JFrame imageFrame = new JFrame("Resim Görüntüleyici");
                    imageFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                    // Resmi gösterecek olan JLabel
                    JLabel label = new JLabel(scaledIcon);
                    imageFrame.add(label);

                    // Frame boyutlarını ayarlıyoruz ve gösteriyoruz
                    imageFrame.pack();  // İçeriği sığdırmak için
                    imageFrame.setLocationRelativeTo(null); // Frame'i ekrana ortalıyoruz
                    imageFrame.setVisible(true);
                }
            }else{
                jLabel3.setText("yanlış ID");
            }

        } catch (SQLException | IOException e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments nurhatın bu
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullaniciekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullaniciekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullaniciekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullaniciekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullaniciekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton kull_ekr_aidat_jbtn;
    private javax.swing.JButton kull_ekr_bin_gideri_jbtn;
    private javax.swing.JTable kull_ekr_tbl1;
    private javax.swing.JTable kull_ekr_tbl2;
    private javax.swing.JLabel kull_ekr_ust_lbl1;
    private javax.swing.JLabel kull_ekr_ustlbl2;
    private javax.swing.JPanel kullanicitablomain_panel;
    // End of variables declaration//GEN-END:variables
}
