/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apartmanotomasyonu;

import java.awt.CardLayout;

/**
 *
 * @author Nurhat
 */
public class kullaniciekrani extends javax.swing.JFrame {

    /**
     * Creates new form kullaniciekrani
     */
    public kullaniciekrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kull_ekr_ust_lbl1 = new javax.swing.JLabel();
        kull_ekr_ustlbl2 = new javax.swing.JLabel();
        dek_alani_lbl = new javax.swing.JLabel();
        kull_ekr_bin_gideri_jbtn = new javax.swing.JButton();
        kull_ekr_aidat_jbtn = new javax.swing.JButton();
        kullanicitablomain_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kull_ekr_tbl1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        kull_ekr_tbl2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kull_ekr_ust_lbl1.setBackground(new java.awt.Color(51, 255, 0));
        kull_ekr_ust_lbl1.setText("Bu ayki aidatı ödediniz.");
        kull_ekr_ust_lbl1.setOpaque(true);

        kull_ekr_ustlbl2.setBackground(new java.awt.Color(51, 255, 0));
        kull_ekr_ustlbl2.setText("Ekstra bina masrafını ödediniz.");
        kull_ekr_ustlbl2.setOpaque(true);

        dek_alani_lbl.setBackground(new java.awt.Color(255, 0, 0));
        dek_alani_lbl.setOpaque(true);

        kull_ekr_bin_gideri_jbtn.setBackground(new java.awt.Color(255, 0, 0));
        kull_ekr_bin_gideri_jbtn.setText("Bina giderleri");
        kull_ekr_bin_gideri_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kull_ekr_bin_gideri_jbtnActionPerformed(evt);
            }
        });

        kull_ekr_aidat_jbtn.setBackground(new java.awt.Color(0, 0, 255));
        kull_ekr_aidat_jbtn.setText("Aidatlarınız");
        kull_ekr_aidat_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kull_ekr_aidat_jbtnActionPerformed(evt);
            }
        });

        kullanicitablomain_panel.setLayout(new java.awt.CardLayout());

        kull_ekr_tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(kull_ekr_tbl1);

        kullanicitablomain_panel.add(jScrollPane1, "card2");

        kull_ekr_tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(kull_ekr_tbl2);

        kullanicitablomain_panel.add(jScrollPane2, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kull_ekr_ust_lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kull_ekr_ustlbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(kull_ekr_bin_gideri_jbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kull_ekr_aidat_jbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dek_alani_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kullanicitablomain_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kull_ekr_ust_lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kull_ekr_ustlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kull_ekr_bin_gideri_jbtn)
                            .addComponent(kull_ekr_aidat_jbtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dek_alani_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kullanicitablomain_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kull_ekr_aidat_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kull_ekr_aidat_jbtnActionPerformed
        CardLayout card = (CardLayout) kullanicitablomain_panel.getLayout();
        card.show(kullanicitablomain_panel, "card3");
    }//GEN-LAST:event_kull_ekr_aidat_jbtnActionPerformed

    private void kull_ekr_bin_gideri_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kull_ekr_bin_gideri_jbtnActionPerformed
        CardLayout card = (CardLayout) kullanicitablomain_panel.getLayout();
        card.show(kullanicitablomain_panel, "card2");
    }//GEN-LAST:event_kull_ekr_bin_gideri_jbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullaniciekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullaniciekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullaniciekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullaniciekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullaniciekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dek_alani_lbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kull_ekr_aidat_jbtn;
    private javax.swing.JButton kull_ekr_bin_gideri_jbtn;
    private javax.swing.JTable kull_ekr_tbl1;
    private javax.swing.JTable kull_ekr_tbl2;
    private javax.swing.JLabel kull_ekr_ust_lbl1;
    private javax.swing.JLabel kull_ekr_ustlbl2;
    private javax.swing.JPanel kullanicitablomain_panel;
    // End of variables declaration//GEN-END:variables
}
