/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apartmanotomasyonu;

import java.awt.Color;

/**
 *
 * @author MONSTERGAMİNG
 */
public class SifremiUnuttum extends javax.swing.JFrame {

    /**
     * Creates new form SifremiUnuttum
     */
    public SifremiUnuttum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sifremi_unuttum_jlbl = new javax.swing.JLabel();
        tel_no_gir_lbl = new javax.swing.JLabel();
        Sif_unt_tel_no_jlbl = new javax.swing.JLabel();
        Sif_Unt_ulkekodu_jcmb = new javax.swing.JComboBox<>();
        Sif_Unt_tel_no_jtf = new javax.swing.JTextField();
        Sif_Unt_kon_jlbl = new javax.swing.JLabel();
        Sif_Unt_yenisifre_jlbl = new javax.swing.JLabel();
        Sif_Unt_yenisifretekrar_lbl = new javax.swing.JLabel();
        sif_unt_yeni_sif_pwf = new javax.swing.JPasswordField();
        sif_unt_yenisifretekrar_pwf = new javax.swing.JPasswordField();
        Sif_Gün_jbtn = new javax.swing.JButton();
        Sif_Unt_binano_kon_jlbl = new javax.swing.JLabel();
        Sif_Unt_binano_jtf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sifremi_unuttum_jlbl.setText("ŞİFREMİ UNUTTUM");

        tel_no_gir_lbl.setText("Lütfen kaydolurken kullandığınız telefon numarasını ve bina nonuzu giriniz");

        Sif_unt_tel_no_jlbl.setText("Telefon NO : ");

        Sif_Unt_ulkekodu_jcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Sif_Unt_tel_no_jtf.setText(" ");

        Sif_Unt_kon_jlbl.setText(" ");

        Sif_Unt_yenisifre_jlbl.setText("Yeni Şifre :");

        Sif_Unt_yenisifretekrar_lbl.setText("Şifre Tekrarı : ");

        Sif_Gün_jbtn.setText("Şifremi Güncelle");
        Sif_Gün_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sif_Gün_jbtnActionPerformed(evt);
            }
        });

        Sif_Unt_binano_kon_jlbl.setText("Bina NO :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Sifremi_unuttum_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sif_Unt_kon_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Sif_Unt_yenisifre_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Sif_Unt_yenisifretekrar_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sif_unt_yenisifretekrar_pwf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sif_unt_yeni_sif_pwf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(Sif_Gün_jbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Sif_Unt_binano_kon_jlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Sif_unt_tel_no_jlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Sif_Unt_ulkekodu_jcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Sif_Unt_tel_no_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Sif_Unt_binano_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tel_no_gir_lbl)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Sifremi_unuttum_jlbl)
                .addGap(18, 18, 18)
                .addComponent(tel_no_gir_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sif_Unt_binano_kon_jlbl)
                    .addComponent(Sif_Unt_binano_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sif_unt_tel_no_jlbl)
                    .addComponent(Sif_Unt_ulkekodu_jcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sif_Unt_tel_no_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sif_Unt_yenisifre_jlbl)
                    .addComponent(sif_unt_yeni_sif_pwf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sif_Unt_yenisifretekrar_lbl)
                    .addComponent(sif_unt_yenisifretekrar_pwf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sif_Unt_kon_jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sif_Gün_jbtn)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sif_Gün_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sif_Gün_jbtnActionPerformed
    String telefonNumarasi = Sif_Unt_tel_no_jtf.getText();
    String yeniSifre = new String(sif_unt_yeni_sif_pwf.getPassword());
    String yeniSifreTekrar = new String(sif_unt_yenisifretekrar_pwf.getPassword());

    if (!yeniSifre.equals(yeniSifreTekrar)) {
        // Mesajı JLabel üzerinde göster
        Sif_Unt_kon_jlbl.setText("Şifreler uyuşmuyor. Lütfen tekrar deneyin.");
        Sif_Unt_kon_jlbl.setForeground(Color.RED);       
        return; 
    }
  
    }//GEN-LAST:event_Sif_Gün_jbtnActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SifremiUnuttum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sif_Gün_jbtn;
    private javax.swing.JTextField Sif_Unt_binano_jtf;
    private javax.swing.JLabel Sif_Unt_binano_kon_jlbl;
    private javax.swing.JLabel Sif_Unt_kon_jlbl;
    private javax.swing.JTextField Sif_Unt_tel_no_jtf;
    private javax.swing.JComboBox<String> Sif_Unt_ulkekodu_jcmb;
    private javax.swing.JLabel Sif_Unt_yenisifre_jlbl;
    private javax.swing.JLabel Sif_Unt_yenisifretekrar_lbl;
    private javax.swing.JLabel Sif_unt_tel_no_jlbl;
    private javax.swing.JLabel Sifremi_unuttum_jlbl;
    private javax.swing.JPasswordField sif_unt_yeni_sif_pwf;
    private javax.swing.JPasswordField sif_unt_yenisifretekrar_pwf;
    private javax.swing.JLabel tel_no_gir_lbl;
    // End of variables declaration//GEN-END:variables
}
