/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apartmanotomasyonu;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nurhat
 */
public class yöneticiekrani extends javax.swing.JFrame {

    /**
     * Creates new form yöneticiekraniykf
     */
    public yöneticiekrani() {

        initComponents();
        setLocationRelativeTo(null);
        setInitialDate();
        gelirlerdoldur();
        aidatyaz();
        butceyaz();
        cmbdolur();
        tabloyuDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gelirler_btn = new javax.swing.JButton();
        giderler_btn = new javax.swing.JButton();
        Aidat_belirleme_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        yoneticimain_panel = new javax.swing.JPanel();
        gelirler_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        aidatmiktari = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        daireno_cmb = new javax.swing.JComboBox<>();
        gelirtarih = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        aidat_ode_jbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Gelir_table = new javax.swing.JTable();
        giderler_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        digergider_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        digergider_tf = new javax.swing.JTextField();
        gidertarih_tf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        dekontyukleme_btn = new javax.swing.JButton();
        imagelabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        görüntüle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        aidatbelirle_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aidat_belirleme_spinner = new javax.swing.JSpinner();
        Aidatonayla_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        butce_lbl = new javax.swing.JLabel();
        aidat_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YÖNETİCİ");

        gelirler_btn.setBackground(new java.awt.Color(51, 255, 0));
        gelirler_btn.setText("GELİRLER");
        gelirler_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gelirler_btnActionPerformed(evt);
            }
        });

        giderler_btn.setBackground(new java.awt.Color(255, 0, 0));
        giderler_btn.setText("GİDERLER");
        giderler_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giderler_btnActionPerformed(evt);
            }
        });

        Aidat_belirleme_btn.setBackground(new java.awt.Color(0, 0, 255));
        Aidat_belirleme_btn.setText("AİDAT BELİRLE");
        Aidat_belirleme_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aidat_belirleme_btnActionPerformed(evt);
            }
        });

        yoneticimain_panel.setLayout(new java.awt.CardLayout());

        gelirler_panel.setBackground(new java.awt.Color(51, 255, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("GELİRLER");

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Miktar Giriniz :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Daire No : ");

        daireno_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        daireno_cmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                daireno_cmbİtemStateChanged(evt);
            }
        });

        gelirtarih.setText("GG/AA/YY");
        gelirtarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gelirtarihActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tarih Giriniz");

        jButton1.setText("ONAYLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        aidat_ode_jbutton.setText("Aidat Öde");
        aidat_ode_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aidat_ode_jbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aidatmiktari)
                    .addComponent(daireno_cmb, 0, 110, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(aidat_ode_jbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gelirtarih, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aidatmiktari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(gelirtarih, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(aidat_ode_jbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(daireno_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Gelir_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Gelir_table);

        javax.swing.GroupLayout gelirler_panelLayout = new javax.swing.GroupLayout(gelirler_panel);
        gelirler_panel.setLayout(gelirler_panelLayout);
        gelirler_panelLayout.setHorizontalGroup(
            gelirler_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gelirler_panelLayout.createSequentialGroup()
                .addGroup(gelirler_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gelirler_panelLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 554, Short.MAX_VALUE))
                    .addGroup(gelirler_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        gelirler_panelLayout.setVerticalGroup(
            gelirler_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gelirler_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );

        yoneticimain_panel.add(gelirler_panel, "card2");

        giderler_panel.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("GİDERLER");

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jCheckBox1.setText("Elektrik");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Su");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Diğer giderler");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Doğalgaz");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Asansör Bakımı");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("Bahçıvan");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Bu giderin ne oldoğuyla ilgili kısa bir bilgi veriniz.");

        digergider_tf.setEnabled(false);

        javax.swing.GroupLayout digergider_panelLayout = new javax.swing.GroupLayout(digergider_panel);
        digergider_panel.setLayout(digergider_panelLayout);
        digergider_panelLayout.setHorizontalGroup(
            digergider_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digergider_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(digergider_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(digergider_panelLayout.createSequentialGroup()
                        .addComponent(digergider_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        digergider_panelLayout.setVerticalGroup(
            digergider_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digergider_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digergider_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(digergider_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addGap(5, 5, 5)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digergider_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        gidertarih_tf.setText("GG/AA/YY");
        gidertarih_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gidertarih_tfActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tarih Giriniz :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Miktar giriniz :");

        jButton2.setText("ONAYLA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dekontyukleme_btn.setText("Dekont resmi yükle");
        dekontyukleme_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dekontyukleme_btnActionPerformed(evt);
            }
        });

        jLabel15.setText("Tablodaki dekont resmini görüntüle");

        jLabel16.setText("Dekont ID:");

        jButton3.setText("dekontu görüntüle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        görüntüle.setText("götüntüle");
        görüntüle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                görüntüleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dekontyukleme_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gidertarih_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jSpinner1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(görüntüle))
                    .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gidertarih_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(17, 17, 17)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dekontyukleme_btn)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(görüntüle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout giderler_panelLayout = new javax.swing.GroupLayout(giderler_panel);
        giderler_panel.setLayout(giderler_panelLayout);
        giderler_panelLayout.setHorizontalGroup(
            giderler_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(giderler_panelLayout.createSequentialGroup()
                .addGroup(giderler_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, giderler_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(giderler_panelLayout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 529, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        giderler_panelLayout.setVerticalGroup(
            giderler_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(giderler_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        yoneticimain_panel.add(giderler_panel, "card3");

        aidatbelirle_panel.setBackground(new java.awt.Color(0, 0, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("AİDAT BELİRLE");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Bu Ayki Aidat Miktarını Giriniz :");

        Aidatonayla_btn.setText("ONAYLA");
        Aidatonayla_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aidatonayla_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aidatbelirle_panelLayout = new javax.swing.GroupLayout(aidatbelirle_panel);
        aidatbelirle_panel.setLayout(aidatbelirle_panelLayout);
        aidatbelirle_panelLayout.setHorizontalGroup(
            aidatbelirle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aidatbelirle_panelLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(aidatbelirle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(aidatbelirle_panelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(aidat_belirleme_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(aidatbelirle_panelLayout.createSequentialGroup()
                .addGroup(aidatbelirle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aidatbelirle_panelLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(Aidatonayla_btn))
                    .addGroup(aidatbelirle_panelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aidatbelirle_panelLayout.setVerticalGroup(
            aidatbelirle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aidatbelirle_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aidatbelirle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGap(47, 47, 47)
                .addGroup(aidatbelirle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(aidat_belirleme_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(Aidatonayla_btn)
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addContainerGap(516, Short.MAX_VALUE))
        );

        yoneticimain_panel.add(aidatbelirle_panel, "card4");

        jScrollPane3.setViewportView(yoneticimain_panel);

        butce_lbl.setText("Bütçe: ");

        aidat_lbl.setText("Aidat: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gelirler_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(giderler_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Aidat_belirleme_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aidat_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(butce_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gelirler_btn)
                    .addComponent(giderler_btn)
                    .addComponent(Aidat_belirleme_btn)
                    .addComponent(butce_lbl)
                    .addComponent(aidat_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gelirtarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gelirtarihActionPerformed
        setInitialDate();
    }//GEN-LAST:event_gelirtarihActionPerformed
    private void butceyaz() {
        SQLHelper dbhelper = new SQLHelper();

        String sql = "SELECT sum(miktar) toplam FROM aidat_gelirleri_table WHERE Bina_No = ?";

        int toplam = 0;
        try (ResultSet rs = dbhelper.executeQuery(sql, girisekranı.bina_no)) {

            if (rs.next()) {
                toplam = rs.getInt("toplam");

            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }
        String sql2 = "SELECT sum(miktar) toplam FROM Bina_Giderleri_table WHERE Bina_No = ?";

        int toplam2;
        try (ResultSet rs = dbhelper.executeQuery(sql2, girisekranı.bina_no)) {

            if (rs.next()) {
                toplam2 = rs.getInt("toplam");

                butce_lbl.setText("Bütçe: " + (toplam - toplam2));
            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }

    }
    private int aidat;

    private void aidatyaz() {
        SQLHelper dbhelper = new SQLHelper();

        String sql = "SELECT aidat FROM yötici_kayitlari_table WHERE Bina_No = ?";
        daireno_cmb.removeAllItems();
        try (ResultSet rs = dbhelper.executeQuery(sql, girisekranı.bina_no)) {

            if (rs.next()) {
                aidat = rs.getInt("aidat");
                aidat_lbl.setText("Aidat: " + aidat);
            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }
    }

    public void gelirlerdoldur() {
        SQLHelper dbhelper = new SQLHelper();

        String sql = "SELECT bina_no, Daire_no, Tarih, miktar FROM aidat_gelirleri_table where Bina_no=?";

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Bina No");
        model.addColumn("Daire No");
        model.addColumn("Tarih");

        model.addColumn("Miktar (TL)");

        try (ResultSet rs = dbhelper.executeQuery(sql, girisekranı.bina_no)) {

            while (rs.next()) {

                Vector<Object> row = new Vector<>();

                row.add(rs.getInt("bina_no"));
                row.add(rs.getString("Daire_no"));
                row.add(rs.getString("Tarih"));
                row.add(rs.getObject("miktar"));

                // Her satır için bir buton yerleştirme
                model.addRow(row);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        Gelir_table.setModel(model);

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SQLHelper dbhelper = new SQLHelper();
        String insertSQL = "INSERT INTO aidat_gelirleri_table (bina_No, Daire_No,Tarih,miktar) VALUES (?, ?, ?,?)";
        String secilenVeri = (String) daireno_cmb.getSelectedItem();
        int index = secilenVeri.indexOf(": ");
        String daireNoStr = secilenVeri.substring(index + 2);

        // Veritabanına ekleme işlemi
        int result = dbhelper.executeUpdate(insertSQL, girisekranı.bina_no, daireNoStr, gelirtarih.getText(), aidatmiktari.getValue());
        if (result > 0) {
            System.out.println("Veri başarıyla eklendi." + result);
        } else {
            jLabel13.setText("Veri ekleme başarısız.");
            System.err.println("Veri ekleme başarısız.");
        }
        dbhelper.close();

        if (result > 0) {
            System.out.println("Kayıt başarıyla eklendi!");
            jLabel13.setText("Kayıt başarıyla eklendi!");
        }
        gelirlerdoldur();
        butceyaz();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void daireno_cmbİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_daireno_cmbİtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_daireno_cmbİtemStateChanged

    private void gelirler_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gelirler_btnActionPerformed
        CardLayout card = (CardLayout) yoneticimain_panel.getLayout();
        card.show(yoneticimain_panel, "card2");

    }//GEN-LAST:event_gelirler_btnActionPerformed

    private void giderler_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giderler_btnActionPerformed
        CardLayout card = (CardLayout) yoneticimain_panel.getLayout();
        card.show(yoneticimain_panel, "card3");
    }//GEN-LAST:event_giderler_btnActionPerformed

    private void Aidat_belirleme_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aidat_belirleme_btnActionPerformed
        CardLayout card = (CardLayout) yoneticimain_panel.getLayout();
        card.show(yoneticimain_panel, "card4");
    }//GEN-LAST:event_Aidat_belirleme_btnActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if (jCheckBox4.isSelected()) {
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox1.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            digergider_panel.setEnabled(false);
            jLabel8.setEnabled(false);
            digergider_panel.setBackground(Color.LIGHT_GRAY);
            jLabel8.setBackground(Color.GRAY);
            digergider_tf.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed

        if (jCheckBox3.isSelected()) {
            jCheckBox2.setSelected(false);
            jCheckBox1.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            digergider_panel.setEnabled(true);
            jLabel8.setEnabled(true);
            digergider_panel.setBackground(Color.WHITE);
            jLabel8.setForeground(Color.black);
            digergider_tf.setEnabled(true);

        } else {
            digergider_panel.setEnabled(false);
            jLabel8.setEnabled(false);
            digergider_panel.setBackground(Color.LIGHT_GRAY);
            jLabel8.setBackground(Color.GRAY);
            digergider_tf.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed
    private void cmbdolur() {

        // SQL bağlantı bilgileri
        SQLHelper dbhelper = new SQLHelper();

        String sql = "SELECT Daire_Sayısı FROM yötici_kayitlari_table WHERE Bina_No = ?";
        daireno_cmb.removeAllItems();
        try (ResultSet rs = dbhelper.executeQuery(sql, girisekranı.bina_no)) {

            if (rs.next()) {
                int daireSayisi = rs.getInt("Daire_Sayısı");
                System.err.println(daireSayisi);

                // Şimdi daire numaralarını ComboBox'a ekleyelim
                for (int i = 1; i <= daireSayisi; i++) {
                    daireno_cmb.addItem("Daire No: " + i);
                }
            } else {
                daireno_cmb.removeAllItems(); // Kayıt bulunmazsa ComboBox'u temizleyin
            }
        } catch (SQLException e) {
            System.err.println("Veri çekme hatası: " + e.getMessage());
        }

    }
    private void gidertarih_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gidertarih_tfActionPerformed
        setInitialDate();
    }//GEN-LAST:event_gidertarih_tfActionPerformed
    private void setInitialDate() {
        LocalDate tarih = LocalDate.now();
        DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        gidertarih_tf.setText(tarih.format(format));
        gelirtarih.setText(tarih.format(format));
    }
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            digergider_panel.setEnabled(false);
            jLabel8.setEnabled(false);
            digergider_panel.setBackground(Color.LIGHT_GRAY);
            jLabel8.setBackground(Color.GRAY);
            digergider_tf.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()) {
            jCheckBox1.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            digergider_panel.setEnabled(false);
            jLabel8.setEnabled(false);
            digergider_panel.setBackground(Color.LIGHT_GRAY);
            jLabel8.setBackground(Color.GRAY);
            digergider_tf.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        if (jCheckBox6.isSelected()) {
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox1.setSelected(false);
            digergider_panel.setEnabled(false);
            jLabel8.setEnabled(false);
            digergider_panel.setBackground(Color.LIGHT_GRAY);
            jLabel8.setBackground(Color.GRAY);
            digergider_tf.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if (jCheckBox5.isSelected()) {
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox1.setSelected(false);
            jCheckBox6.setSelected(false);
            digergider_panel.setEnabled(false);
            jLabel8.setEnabled(false);
            digergider_panel.setBackground(Color.LIGHT_GRAY);
            jLabel8.setBackground(Color.GRAY);
            digergider_tf.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed
    private String resimyolu;
    private void dekontyukleme_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dekontyukleme_btnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:/path/to/Resimler"));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            resimyolu = selectedFile.getAbsolutePath(); // Dosya yolunu atıyoruz
            imagelabel.setText(resimyolu);
            dekontuac(); // Resmi aFçıyoruz
        }
    }//GEN-LAST:event_dekontyukleme_btnActionPerformed
    private void dekontuac() {

        try {
            BufferedImage image = ImageIO.read(new File(resimyolu)); // Dosya yolunu buradan alır
            // Ekran boyutlarını alıyoruz
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int screenWidth = (int) screenSize.getWidth();
            int screenHeight = (int) screenSize.getHeight();

            // Resmin boyutlarını ekran boyutuna göre ayarlıyoruz
            int imgWidth = image.getWidth();
            int imgHeight = image.getHeight();

            // Resmin boyutunu ekran boyutlarına sığacak şekilde yeniden boyutlandırıyoruz
            int newWidth = Math.min(imgWidth, screenWidth - 100); // Ekranın biraz daha küçük olması için 100 piksel boşluk bırakıyoruz
            int newHeight = Math.min(imgHeight, screenHeight - 100); // Aynı şekilde yükseklik için de

            // Resmi yeniden boyutlandırıyoruz
            Image scaledImage = image.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            // Yeni bir frame açıyoruz
            JFrame imageFrame = new JFrame("Resim Görüntüleyici");
            imageFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            // Resmi gösterecek olan JLabel
            JLabel label = new JLabel(scaledIcon);
            imageFrame.add(label);

            // Frame boyutlarını ayarlıyoruz ve gösteriyoruz
            imageFrame.pack();  // İçeriği sığdırmak için
            imageFrame.setLocationRelativeTo(null); // Frame'i ekrana ortalıyoruz
            imageFrame.setVisible(true);
        } catch (IOException | NullPointerException e) {

            JOptionPane.showMessageDialog(this, "Resim yüklenemedi!", "Hata", JOptionPane.ERROR_MESSAGE);

        }

    }
    private void Aidatonayla_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aidatonayla_btnActionPerformed
        SQLHelper sql = new SQLHelper();
        String insertSQL = "UPDATE yötici_kayitlari_table SET aidat = ? WHERE Bina_No = ?";

        // Veritabanına ekleme işlemi
        int result = sql.executeUpdate(insertSQL, aidat_belirleme_spinner.getValue(), girisekranı.bina_no);
        if (result > 0) {
            jLabel12.setText("aidat başarıyla güncellendi.");
            System.out.println("Veri başarıyla eklendi.");
        } else {
            System.err.println("Veri ekleme başarısız.");
        }
        sql.close();

        if (result > 0) {
            System.out.println("Kayıt başarıyla eklendi!");

        }
        aidatyaz();

    }//GEN-LAST:event_Aidatonayla_btnActionPerformed
    private void tabloyuDoldur() {
        SQLHelper dphelper = new SQLHelper();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Bina No");
        model.addColumn("Tarih");
        model.addColumn("Gider Türü");
        model.addColumn("Miktar (TL)");
        model.addColumn("Dekont Resmi");

        String selectSQL = "SELECT id,Bina_no, tarih, Gidar_Türü, miktar, dekont FROM Bina_Giderleri_table where Bina_no=?";
        try (ResultSet rs = dphelper.executeQuery(selectSQL, girisekranı.bina_no)) {

            while (rs.next()) {

                Vector<Object> row = new Vector<>();
                row.add(rs.getInt("id"));
                row.add(rs.getInt("Bina_no"));
                row.add(rs.getString("tarih"));
                row.add(rs.getString("Gidar_Türü"));
                row.add(rs.getObject("miktar"));
                row.add(rs.getObject("dekont"));

                // Her satır için bir buton yerleştirme
                model.addRow(row);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        jTable1.setModel(model);
        jTable1.setRowHeight(40); // Satır yüksekliği butonlar için ayarlanır

    }
    private void aidat_ode_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aidat_ode_jbuttonActionPerformed
        aidatmiktari.setValue(aidat);
    }//GEN-LAST:event_aidat_ode_jbuttonActionPerformed

    private void giderisqlegonder(String gider) {
        SQLHelper dbhelper = new SQLHelper();
        String insertSQL = "INSERT INTO Bina_Giderleri_table (Bina_no, tarih, Gidar_Türü, miktar, dekont) VALUES (?, ?, ?, ?, ?)";

        try (FileInputStream fis = new FileInputStream(new File(resimyolu))) {
            int fileLength = (int) new File(resimyolu).length();

            // Veritabanına ekleme işlemi
            int result = dbhelper.executeUpdateresim(insertSQL, girisekranı.bina_no, gelirtarih.getText(), gider, jSpinner1.getValue(), fis, fileLength);

            if (result > 0) {
                System.out.println("Veri başarıyla eklendi.");
                jLabel14.setText("Kayıt başarıyla eklendi!");
            } else {
                jLabel14.setText("Veri ekleme başarısız.");
                System.err.println("Veri ekleme başarısız.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            dbhelper.close();
        }
        tabloyuDoldur();

        // Veritabanına ekleme işlemi
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jCheckBox1.isSelected()) {
            giderisqlegonder("Elektrik");
        } else if (jCheckBox2.isSelected()) {
            giderisqlegonder("Su");
        } else if (jCheckBox4.isSelected()) {
            giderisqlegonder("Doğalgaz");
        } else if (jCheckBox6.isSelected()) {
            giderisqlegonder("Bahçıvan");
        } else if (jCheckBox5.isSelected()) {
            giderisqlegonder("Asansör Bakımı");
        } else if (jCheckBox3.isSelected()) {
            if (digergider_tf.getText().isEmpty()) {
                jLabel14.setText("Lütfen giderin açıklamasını girin!");

            } else {
                giderisqlegonder(digergider_tf.getText());

            }

        } else {
            jLabel14.setText("Lütfen bir gider türü seçin!");
        }
        butceyaz();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SQLHelper dphelper = new SQLHelper();

        String selectSQL = "SELECT dekont FROM Bina_Giderleri_table where id=? and Bina_no=?";
        try (ResultSet rs = dphelper.executeQuery(selectSQL, jSpinner2.getValue(), girisekranı.bina_no)) {
            if (rs.next()) {
                // Veriyi alıyoruz
                byte[] imageBytes = rs.getBytes("dekont");

                if (imageBytes != null) {
                    // Byte dizisini BufferedImage'ye çeviriyoruz
                    InputStream in = new ByteArrayInputStream(imageBytes);
                    BufferedImage img = ImageIO.read(in);

                    // Ekran boyutlarını alıyoruz
                    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                    int screenWidth = (int) screenSize.getWidth();
                    int screenHeight = (int) screenSize.getHeight();

                    // Resmin boyutlarını ekran boyutuna göre ayarlıyoruz
                    int imgWidth = img.getWidth();
                    int imgHeight = img.getHeight();

                    // Resmin boyutunu ekran boyutlarına sığacak şekilde yeniden boyutlandırıyoruz
                    int newWidth = Math.min(imgWidth, screenWidth - 100); // Ekranın biraz daha küçük olması için 100 piksel boşluk bırakıyoruz
                    int newHeight = Math.min(imgHeight, screenHeight - 100); // Aynı şekilde yükseklik için de

                    // Resmi yeniden boyutlandırıyoruz
                    Image scaledImage = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
                    ImageIcon scaledIcon = new ImageIcon(scaledImage);

                    // Yeni bir frame açıyoruz
                    JFrame imageFrame = new JFrame("Resim Görüntüleyici");
                    imageFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                    // Resmi gösterecek olan JLabel
                    JLabel label = new JLabel(scaledIcon);
                    imageFrame.add(label);

                    // Frame boyutlarını ayarlıyoruz ve gösteriyoruz
                    imageFrame.pack();  // İçeriği sığdırmak için
                    imageFrame.setLocationRelativeTo(null); // Frame'i ekrana ortalıyoruz
                    imageFrame.setVisible(true);
                }
            } else {
                jLabel14.setText("yanlış ID");
            }

        } catch (SQLException | IOException e) {

            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void görüntüleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_görüntüleActionPerformed
        dekontuac();


    }//GEN-LAST:event_görüntüleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yöneticiekrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yöneticiekrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yöneticiekrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yöneticiekrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yöneticiekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aidat_belirleme_btn;
    private javax.swing.JButton Aidatonayla_btn;
    private javax.swing.JTable Gelir_table;
    private javax.swing.JSpinner aidat_belirleme_spinner;
    private javax.swing.JLabel aidat_lbl;
    private javax.swing.JButton aidat_ode_jbutton;
    private javax.swing.JPanel aidatbelirle_panel;
    private javax.swing.JSpinner aidatmiktari;
    private javax.swing.JLabel butce_lbl;
    private javax.swing.JComboBox<String> daireno_cmb;
    private javax.swing.JButton dekontyukleme_btn;
    private javax.swing.JPanel digergider_panel;
    private javax.swing.JTextField digergider_tf;
    private javax.swing.JButton gelirler_btn;
    private javax.swing.JPanel gelirler_panel;
    private javax.swing.JTextField gelirtarih;
    private javax.swing.JButton giderler_btn;
    private javax.swing.JPanel giderler_panel;
    private javax.swing.JTextField gidertarih_tf;
    private javax.swing.JButton görüntüle;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel yoneticimain_panel;
    // End of variables declaration//GEN-END:variables
}
